#ifndef SHAREDLIBRAY_GLOBAL_H
#define SHAREDLIBRAY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHAREDLIBRAY_LIBRARY)
#  define SHAREDLIBRAYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHAREDLIBRAYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SHAREDLIBRAY_GLOBAL_H
