#ifndef MP5800_API_GLOBAL_H
#define MP5800_API_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MP5800_API_LIBRARY)
#  define MP5800_APISHARED_EXPORT Q_DECL_EXPORT
#else
#  define MP5800_APISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MP5800_API_GLOBAL_H
